// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PmQL.Data;

#nullable disable

namespace PmQL.Migrations
{
    [DbContext(typeof(PmQlContext))]
    [Migration("20250320013536_AddTableUser")]
    partial class AddTableUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PmQL.Models.FmpA0", b =>
                {
                    b.Property<string>("Giá")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Ngày")
                        .HasColumnType("float");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("FMP_A0$");
                });

            modelBuilder.Entity("PmQL.Models.FmpEvn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<string>("Gia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__FMP_EVN__3214EC276D4638BE");

                    b.ToTable("FMP_EVN");
                });

            modelBuilder.Entity("PmQL.Models.FmpSai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__FMP_Sai__3214EC2740C9C5B8");

                    b.ToTable("FMP_Sai");
                });

            modelBuilder.Entity("PmQL.Models.NhậpGiáNm", b =>
                {
                    b.Property<string>("Giá")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Ngày")
                        .HasColumnType("float");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("'Nhập giá NM$'");
                });

            modelBuilder.Entity("PmQL.Models.PmA0", b =>
                {
                    b.Property<string>("Giá")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Ngày")
                        .HasColumnType("float");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("Pm_A0$");
                });

            modelBuilder.Entity("PmQL.Models.PmEvn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<string>("Gia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Pm_EVN__3214EC276B0DD338");

                    b.ToTable("Pm_EVN");
                });

            modelBuilder.Entity("PmQL.Models.PmSai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChuKy0h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_0h30");

                    b.Property<double?>("ChuKy10h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h");

                    b.Property<double?>("ChuKy10h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_10h30");

                    b.Property<double?>("ChuKy11h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h");

                    b.Property<double?>("ChuKy11h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_11h30");

                    b.Property<double?>("ChuKy12h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h");

                    b.Property<double?>("ChuKy12h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_12h30");

                    b.Property<double?>("ChuKy13h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h");

                    b.Property<double?>("ChuKy13h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_13h30");

                    b.Property<double?>("ChuKy14h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h");

                    b.Property<double?>("ChuKy14h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_14h30");

                    b.Property<double?>("ChuKy15h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h");

                    b.Property<double?>("ChuKy15h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_15h30");

                    b.Property<double?>("ChuKy16h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h");

                    b.Property<double?>("ChuKy16h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_16h30");

                    b.Property<double?>("ChuKy17h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h");

                    b.Property<double?>("ChuKy17h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_17h30");

                    b.Property<double?>("ChuKy18h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h");

                    b.Property<double?>("ChuKy18h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_18h30");

                    b.Property<double?>("ChuKy19h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h");

                    b.Property<double?>("ChuKy19h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_19h30");

                    b.Property<double?>("ChuKy1h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h");

                    b.Property<double?>("ChuKy1h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_1h30");

                    b.Property<double?>("ChuKy20h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h");

                    b.Property<double?>("ChuKy20h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_20h30");

                    b.Property<double?>("ChuKy21h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h");

                    b.Property<double?>("ChuKy21h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_21h30");

                    b.Property<double?>("ChuKy22h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h");

                    b.Property<double?>("ChuKy22h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_22h30");

                    b.Property<double?>("ChuKy23h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h");

                    b.Property<double?>("ChuKy23h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_23h30");

                    b.Property<double?>("ChuKy24h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_24h");

                    b.Property<double?>("ChuKy2h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h");

                    b.Property<double?>("ChuKy2h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_2h30");

                    b.Property<double?>("ChuKy3h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h");

                    b.Property<double?>("ChuKy3h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_3h30");

                    b.Property<double?>("ChuKy4h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h");

                    b.Property<double?>("ChuKy4h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_4h30");

                    b.Property<double?>("ChuKy5h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h");

                    b.Property<double?>("ChuKy5h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_5h30");

                    b.Property<double?>("ChuKy6h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h");

                    b.Property<double?>("ChuKy6h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_6h30");

                    b.Property<double?>("ChuKy7h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h");

                    b.Property<double?>("ChuKy7h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_7h30");

                    b.Property<double?>("ChuKy8h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h");

                    b.Property<double?>("ChuKy8h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_8h30");

                    b.Property<double?>("ChuKy9h")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h");

                    b.Property<double?>("ChuKy9h30")
                        .HasColumnType("float")
                        .HasColumnName("ChuKy_9h30");

                    b.Property<string>("Gia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<double?>("Tong")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Pm_Sai__3214EC27797439AB");

                    b.ToTable("Pm_Sai");
                });

            modelBuilder.Entity("PmQL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
